import Head from 'next/head';
import { useState } from 'react';
import Brands from '../components/Brands';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Slider from '../components/Slider';

export default function Home() {
  const [logedIn, setLogedIn] = useState(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header logedIn={logedIn} setLogedIn={setLogedIn} />
      {!logedIn ? (
        <Hero />
      ) : (
        <main>
          <Slider />
          <Brands />
        </main>
      )}
    </div>
  );
}

export async function getServerSideProps(ctx) {
  return {
    props: {},
  };
}
